### ISSUE TITLE
Question about the index.js file in the each folder of container?

### ISSUE THREAD

**Issue by LeoTianJLL** [asimolmez/react-native-folder-structure#1]
Hi @asimolmez , this is really helpful and I have used this folder structure in my project. However, I am not sure how to write `index.js` file in the subfolder of container folder, like `container/Signin/index.js`.  One more thing that I want to know is how to combine `react-navigation` related files with this folder structure?

**Comment by asimolmez** [comment]
1. I think we do not need to `index.js` file because only navigation class should access to containers. 
2. Actually i did not want to combine navigation because it depends to project size.

Sorry for late reply...
